spring.application.name=Hibernet_sample
Spring.dataSource.username=postgres
Spring.dataSource.password=Purva@2878
Spring.dataSource.url=jdbc:postgres://localhoast:5432?ssit

Spring.jpa.hibernet.ddl.auto=update
Spring.jpa.show-sql=true
Spring.jpa.properties.hibernet.format_sql=true
Spring.jpa.database.platforms.hibernet.dialect.postgresSQLDialect